server:
  port: 8989
  servlet:
    context-path: /ems
spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/menu?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  web:
    #暴露哪些资源可以通过项目名访问
    resources:
      static-locations: classpath:/static/,file:${img.file.dir}
  cloud:
    nacos:
        discovery:
          server-addr: 127.0.0.1:8848
  application:
    name: menu

logging:
  level:
    root: info
    com.example.emsthymeleaf: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.emsthymeleaf.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 上传文件路径
img:
  file:
    dir: D:\web\files